# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK treo650"
product_name = "RMK treo650"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "xvzan"
chip = "nrf52840"

[matrix]
# 行引脚（row-gpios）
input_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]
# 列引脚（col-gpios）
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
# 二极管方向：col2row
# 注意：RMK 本地编译时方向在 feature gate 里设置，这里只有云编译时才生效
# row2col = false


[layout]
rows = 6
cols = 8
layers = 1
keymap = [
    [
        # row0
        ["K0_0", "K0_1", "K0_2", "K0_3", "K0_4", "K0_5", "K0_6", "K0_7"],

        # row1
        ["_", "K1_1", "K1_2", "K1_3", "K1_4", "K1_5", "K1_6", "K1_7"],

        # row2
        ["_", "K2_1", "K2_2", "K2_3", "K2_4", "K2_5", "K2_6", "K2_7"],

        # row3
        ["K3_0", "K3_1", "K3_2", "K3_3", "K3_4", "K3_5", "K3_6", "K3_7"],

        # row4
        ["K4_0", "K4_1", "K4_2", "K4_3", "K4_4", "K4_5", "K4_6", "K4_7"],

        # row5
        ["K5_0", "K5_1", "K5_2", "K5_3", "K5_4", "K5_5", "K5_6", "K5_7"],
    ],
]


[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false