# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK treo650"
product_name = "RMK treo650"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "xvzan"
chip = "nrf52840"

[matrix]
# 行引脚（row-gpios）
row_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11"]
# 列引脚（col-gpios）
col_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
# 二极管方向：col2row
# 注意：RMK 本地编译时方向在 feature gate 里设置，这里只有云编译时才生效
# row2col = false


[layout]
rows = 6
cols = 8
layers = 2
keymap = [
    [
        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["_", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["_", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],
    ],
    [
        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["_", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["_", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],

        # row
        ["K", "K", "K", "K", "K", "K", "K", "K"],
    ],
]


[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false